server:
  port: 9090
  error:
    include-stacktrace: never

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'library-client'
            client-secret: '9584640c-3804-4dcd-997b-93593cfb9ea7'
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
          provider:
            keycloak:
              issuerUri: http://localhost:8080/auth/realms/workshop
              user-name-attribute: name

library:
  server: http://localhost:9091
